const fs = require('fs');
let file = fs.readFileSync('src/components/financial/checks/CheckModals.tsx', 'utf8');

file = file.replace(
  /<div className="grid grid-cols-2 gap-4">\s*<div>\s*<label className="block text-xs font-black text-gray-700 mb-1">شناسه صیادی \(۱۶ رقم\) \*<\/label>[\s\S]*?<label className="block text-xs font-black text-gray-700 mb-1">مبلغ چک \(تومان\) \*<\/label>/,
  '<div className="grid grid-cols-2 gap-4">\n                  <div>\n                    <label className="block text-xs font-black text-gray-700 mb-1">شناسه صیادی (۱۶ رقم) *</label>\n                    <input required type="text" value={icSayadId || \'\'} onChange={e => setIcSayadId(e.target.value)} pattern="\\\\d{16}" title="شناسه صیادی باید دقیقاً ۱۶ رقم باشد" className="w-full border rounded-xl px-4 py-2 text-sm font-mono text-center focus:ring-2 focus:ring-indigo-500" dir="ltr" placeholder="1234567890123456" />\n                  </div>\n                  <div>\n                    <label className="block text-xs font-black text-gray-700 mb-1">بابت *</label>\n                    <select required value={icReason || \'خرید کالا\'} onChange={e => setIcReason(e.target.value)} className="w-full border rounded-xl px-4 py-2 text-sm focus:ring-2 focus:ring-indigo-500 bg-white">\n                      <option value="خرید کالا">خرید کالا</option>\n                      <option value="تسویه بدهی">تسویه بدهی</option>\n                      <option value="حقوق و دستمزد">حقوق و دستمزد</option>\n                      <option value="سایر">سایر</option>\n                    </select>\n                  </div>\n                </div>\n                <div>\n                  <label className="block text-xs font-black text-gray-700 mb-1">مبلغ چک (تومان) *</label>'
);

file = file.replace(
  /<div className="grid grid-cols-2 gap-4">\s*<div>\s*<label className="block text-xs font-black text-gray-700 mb-1">شماره چک \*<\/label>/,
  '<div className="grid grid-cols-2 gap-4">\n                  <div>\n                    <label className="block text-xs font-black text-gray-700 mb-1">شناسه صیادی (۱۶ رقم) *</label>\n                    <input required type="text" value={rcSayadId || \'\'} onChange={e => setRcSayadId(e.target.value)} pattern="\\\\d{16}" title="شناسه صیادی باید دقیقاً ۱۶ رقم باشد" className="w-full border rounded-xl px-4 py-2 text-sm font-mono text-center focus:ring-2 focus:ring-indigo-500" dir="ltr" placeholder="1234567890123456" />\n                  </div>\n                  <div>\n                    <label className="block text-xs font-black text-gray-700 mb-1">بابت *</label>\n                    <select required value={rcReason || \'تسویه بدهی\'} onChange={e => setRcReason(e.target.value)} className="w-full border rounded-xl px-4 py-2 text-sm focus:ring-2 focus:ring-indigo-500 bg-white">\n                      <option value="خرید کالا">خرید کالا</option>\n                      <option value="تسویه بدهی">تسویه بدهی</option>\n                      <option value="سایر">سایر</option>\n                    </select>\n                  </div>\n                </div>\n                <div className="grid grid-cols-2 gap-4">\n                  <div>\n                    <label className="block text-xs font-black text-gray-700 mb-1">شماره چک *</label>'
);

fs.writeFileSync('src/components/financial/checks/CheckModals.tsx', file);
