const fs = require('fs');
let code = fs.readFileSync('src/services/syncQueueService.ts', 'utf8');

code = code.replace(
  "export type SyncOperation = 'ADD_PERSON' | 'UPDATE_PERSON' | 'DELETE_PERSON' | 'ADD_PERSON_GROUP' | 'UPDATE_PERSON_GROUP' | 'DELETE_PERSON_GROUP' | 'ADD_PERSON_ROLE' | 'UPDATE_PERSON_ROLE' | 'DELETE_PERSON_ROLE' | 'ADD_PERSON_CATEGORY' | 'UPDATE_PERSON_CATEGORY' | 'DELETE_PERSON_CATEGORY';",
  "export type SyncOperation = 'ADD_PERSON' | 'UPDATE_PERSON' | 'DELETE_PERSON' | 'ADD_PERSON_GROUP' | 'UPDATE_PERSON_GROUP' | 'DELETE_PERSON_GROUP' | 'ADD_PERSON_ROLE' | 'UPDATE_PERSON_ROLE' | 'DELETE_PERSON_ROLE' | 'ADD_PERSON_CATEGORY' | 'UPDATE_PERSON_CATEGORY' | 'DELETE_PERSON_CATEGORY' | 'ADD_PRODUCT' | 'UPDATE_PRODUCT' | 'DELETE_PRODUCT' | 'ADD_PRODUCT_CATEGORY' | 'UPDATE_PRODUCT_CATEGORY' | 'DELETE_PRODUCT_CATEGORY';"
);

fs.writeFileSync('src/services/syncQueueService.ts', code);
console.log('patched SyncOperation');
